# Generated by Django 5.1 on 2026-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_setting_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='allow_zero_stock_sale',
            field=models.BooleanField(default=False),
        ),
    ]
