# Generated by Django 5.2.17 on 2026-08-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_customer_delete_settings_delete_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
    ]
