# Generated by Django 5.2.17 on 2026-08-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
