# Generated by Django 5.2.17 on 2026-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
