# Generated by Django 5.2.17 on 2026-08-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_shop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
