# Generated by Django 5.2.17 on 2026-08-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_merchant_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopsettings',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.shop'),
        ),
    ]
