# Generated by Django 5.2.17 on 2026-08-27 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0003_alter_shop_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='purchases',
        ),
        migrations.CreateModel(
            name='PurchaseBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.PositiveIntegerField(editable=False)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_batches', to='tenants.employee')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.shop')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.purchasebatch'),
        ),
        migrations.AddConstraint(
            model_name='purchasebatch',
            constraint=models.UniqueConstraint(fields=('shop', 'reference_number'), name='unique_purchase_batch_reference_per_shop'),
        ),
    ]
