# Generated by Django 5.1 on 2026-08-08 18:05

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.TextField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, null=True, region=None)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.merchant')),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_percentage', models.FloatField(default=0.0)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_mobile_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mobile_money_covers_total', models.BooleanField(default=False)),
                ('has_sav', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='tenants.employee')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.shop')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total_detail', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.item')),
                ('sale', models.ForeignKey(db_column='sale', on_delete=django.db.models.deletion.CASCADE, related_name='saledetail_set', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sale Detail',
                'verbose_name_plural': 'Sale Details',
                'db_table': 'sale_details',
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('merchant', 'phone'), name='unique_customer_phone_per_merchant'),
        ),
    ]
