# Generated by Django 5.2.17 on 2026-08-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('tenants', '0002_shop_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reference_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('shop', 'reference_number'), name='unique_sale_reference_per_shop'),
        ),
    ]
