# Generated by Django 5.2.17 on 2026-08-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='reference_number',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
