# Generated by Django 5.2.17 on 2026-09-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name_override',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
