# Generated by Django 5.2.17 on 2026-09-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_customer_name_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price at the time of sale', max_digits=10),
        ),
    ]
